flowchart LR
    legend["sample: L0 , nodes<=50, edges_drawn=0 , full_data=JSON"]
    L0_Symbol_61abe46cdc0e["Symbol: if\nkernel/fs/fs.c"]
    L0_Symbol_b6919bc3626b["Symbol: if\nkernel/fs/fat32/fat.c"]
    L0_Symbol_d6c69f1df593["Symbol: if\nkernel/hal/sdcard.c"]
    L0_Symbol_fe2a89521f60["Symbol: if\nkernel/mm/kmalloc.c"]
    L0_Symbol_5635e6aa889b["Symbol: while\nkernel/mm/pm.c"]
    L0_Symbol_706d0895d190["Symbol: printf\nkernel/printf.c"]
    L0_Symbol_bf6de3e5384e["Symbol: printf\nxv6-user/printf.c"]
    L0_AsmLabel_087e9257bf64["AsmLabel: exit\nxv6-user/initcode.S"]
    L0_AsmLabel_1e7a3644654b["AsmLabel: exit\nxv6-user/ostest_asm.S"]
    L0_Symbol_e830625da0d1["Symbol: exit\nkernel/sched/proc.c"]
    L0_Symbol_300e6a7ca010["Symbol: main\nbootloader/SBI/rustsbi-k210/build.rs"]
    L0_Symbol_32e83bf5cf0e["Symbol: main\nbootloader/SBI/rustsbi-k210/src/main.rs"]
    L0_Symbol_4ac28d8e047a["Symbol: main\nbootloader/SBI/rustsbi-k210/src/main.back.rs"]
    L0_Symbol_a73d407f5e15["Symbol: main\nbootloader/SBI/rustsbi-qemu/build.rs"]
    L0_Symbol_c9d8ea311f69["Symbol: main\nbootloader/SBI/rustsbi-qemu/src/main.rs"]
    L0_Symbol_d3598e1cfb28["Symbol: main\nkernel/main.c"]
    L0_Macro_4b7e51a93631["Macro: panic\ninclude/printf.h"]
    L0_Symbol_3579b15e5ebc["Symbol: panic\nxv6-user/sh.c"]
    L0_Symbol_9a0d0c307372["Symbol: panic\nbootloader/SBI/rustsbi-k210/src/main.back.rs"]
    L0_Symbol_d664902c6acc["Symbol: panic\nbootloader/SBI/rustsbi-k210/src/main.rs"]
    L0_Symbol_fc9b69378709["Symbol: panic\nbootloader/SBI/rustsbi-qemu/src/main.rs"]
    L0_Macro_ccf0f2b2f6df["Macro: __debug_info\ninclude/utils/debug.h"]
    L0_Symbol_893a51ee188a["Symbol: memset\nxv6-user/ulib.c"]
    L0_Symbol_9779e663c88c["Symbol: release\nkernel/sync/spinlock.c"]
    L0_Symbol_998f58d3515d["Symbol: acquire\nkernel/sync/spinlock.c"]
    L0_Symbol_d621965cbcc0["Symbol: memset\nkernel/utils/string.c"]
    L0_Symbol_04ad31e4ce91["Symbol: fprintf\nxv6-user/printf.c"]
    L0_Symbol_36c80565c9f7["Symbol: initlock\nkernel/sync/spinlock.c"]
    L0_Macro_c2ae8d61286f["Macro: __debug_warn\ninclude/utils/debug.h"]
    L0_Symbol_2bb11e049722["Symbol: sleep\nkernel/sched/proc.c"]
    L0_AsmLabel_5916d223151d["AsmLabel: wait\nxv6-user/ostest_asm.S"]
    L0_Symbol_af4d55a217e2["Symbol: strlen\nkernel/utils/string.c"]
    L0_Symbol_b54e586dd160["Symbol: strlen\nxv6-user/ulib.c"]
    L0_AsmLabel_dfff27585f6f["AsmLabel: fork\nxv6-user/ostest_asm.S"]
    L0_Symbol_04fdad4abc06["Symbol: memmove\nkernel/utils/string.c"]
    L0_Symbol_455dc0bd5e16["Symbol: kfree\nkernel/mm/kmalloc.c"]
    L0_Symbol_8da53fba7201["Symbol: memmove\nxv6-user/ulib.c"]
    L0_Symbol_6f5826025cdf["Symbol: open\nxv6-user/user.h"]
    L0_Macro_42f6ff7d0128["Macro: freepage\ninclude/mm/pm.h"]
    L0_Macro_399ead494127["Macro: __debug_assert\ninclude/utils/debug.h"]
    L0_Macro_f8e42bee694e["Macro: allocpage\ninclude/mm/pm.h"]
    L0_Symbol_434585d8ff33["Symbol: copyout2\nkernel/syscall/syssignal.c"]
    L0_Symbol_8a2d9f042d57["Symbol: wakeup\nkernel/sched/proc.c"]
    L0_Symbol_e8eb85defe7f["Symbol: copyout2\nkernel/mm/vm.c"]
    L0_AsmLabel_5024901b8298["AsmLabel: exec\nxv6-user/ostest_asm.S"]
    L0_Macro_173a0c339e7f["Macro: container_of\ninclude/types.h"]
    L0_Symbol_1a5da497ab8d["Symbol: ilock\nkernel/fs/fs.c"]
    L0_Symbol_2d7c7736040f["Symbol: exec\nxv6-user/user.h"]
    L0_Symbol_6d53a58da9d8["Symbol: copyout\nxv6-user/usertests.c"]
    L0_Symbol_6d92f1ea26a7["Symbol: strchr\nxv6-user/ulib.c"]
