flowchart LR
    titleNode["L2 MechanismGraph"]
    L2_Assert_f322801c72["Assert: Assert"]
    L2_BlockCache_1bf979fb09["BlockCache: BlockCache"]
    L2_BlockDevice_c2340cf2ba["BlockDevice: BlockDevice"]
    L2_BlockDevice_11939e6551["BlockDevice: BlockDevice"]
    L2_BlockDevice_38fc53a836["BlockDevice: BlockDevice"]
    L2_BootEntry_1d4a70760e["BootEntry: BootEntry"]
    L2_BuildSystem_a8c219d95f["BuildSystem: BuildSystem"]
    L2_BuildSystem_75ec8d0e03["BuildSystem: BuildSystem"]
    L2_BuildSystem_80fa315115["BuildSystem: BuildSystem"]
    L2_BuildSystem_8c152219af["BuildSystem: BuildSystem"]
    L2_BuildSystem_0f67d72b71["BuildSystem: BuildSystem"]
    L2_BuildSystem_1d3dd4dc59["BuildSystem: BuildSystem"]
    L2_BuildSystem_f4e17de2ff["BuildSystem: BuildSystem"]
    L2_BuildSystem_ddfc481e48["BuildSystem: BuildSystem"]
    L2_BuildSystem_eeb3debcbb["BuildSystem: BuildSystem"]
    L2_Context_cac9543bf3["Context: Context"]
    L2_DemandPage_e04e950567["DemandPage: DemandPage"]
    L2_Driver_1093002b6c["Driver: Driver"]
    L2_FileDescriptor_43b9110f0b["FileDescriptor: FileDescriptor"]
    L2_FileSystem_b5d09a04f5["FileSystem: FileSystem"]
    L2_FileSystem_9293eb6513["FileSystem: FileSystem"]
    L2_FileSystem_57f68b0830["FileSystem: FileSystem"]
    L2_FileSystem_dc19f9473c["FileSystem: FileSystem"]
    L2_FileSystem_ffa31db570["FileSystem: FileSystem"]
    L2_FileSystem_3ef2d60737["FileSystem: FileSystem"]
    L2_FileSystem_34c6204c03["FileSystem: FileSystem"]
    L2_FileSystem_c0f039e9e5["FileSystem: FileSystem"]
    L2_FileSystem_2c61ebdb80["FileSystem: FileSystem"]
    L2_FileSystem_aebccffc21["FileSystem: FileSystem"]
    L2_FileSystem_e9432d28a8["FileSystem: FileSystem"]
    L2_FileSystem_f14a21db5c["FileSystem: FileSystem"]
    L2_FileSystem_004009f9f7["FileSystem: FileSystem"]
    L2_FileSystem_be7f9c6cef["FileSystem: FileSystem"]
    L2_FileSystem_95b4156fb2["FileSystem: FileSystem"]
    L2_FileSystem_7543854919["FileSystem: FileSystem"]
    L2_FileSystem_132f35e847["FileSystem: FileSystem"]
    L2_FileSystem_0850b432d2["FileSystem: FileSystem"]
    L2_FileSystem_0c1ffb6f88["FileSystem: FileSystem"]
    L2_FileSystem_8d99a1564c["FileSystem: FileSystem"]
    L2_FileSystem_bf0e5b104d["FileSystem: FileSystem"]
    L2_FileSystem_3eafe550a9["FileSystem: FileSystem"]
    L2_FileSystem_1ae740b45f["FileSystem: FileSystem"]
    L2_FileSystem_9f4e17313a["FileSystem: FileSystem"]
    L2_FileSystem_94e9c05649["FileSystem: FileSystem"]
    L2_FileSystem_cb6ac30371["FileSystem: FileSystem"]
    L2_FileSystem_0af4ced0b5["FileSystem: FileSystem"]
    L2_FileSystem_f39f944561["FileSystem: FileSystem"]
    L2_FileSystem_a5c1c92892["FileSystem: FileSystem"]
    L2_FileSystem_edd0badc6b["FileSystem: FileSystem"]
    L2_FileSystem_902df764de["FileSystem: FileSystem"]
    L2_FileSystem_2b5b33a682["FileSystem: FileSystem"]
    L2_FileSystem_27b4ea84fb["FileSystem: FileSystem"]
    L2_FileSystem_ae3b1c7b37["FileSystem: FileSystem"]
    L2_FileSystem_ea2c07c5e9["FileSystem: FileSystem"]
    L2_FileSystem_58db900928["FileSystem: FileSystem"]
    L2_FileSystem_842dca00f7["FileSystem: FileSystem"]
    L2_FileSystem_3fe873bf86["FileSystem: FileSystem"]
    L2_FileSystem_3a63822063["FileSystem: FileSystem"]
    L2_FileSystem_ec9c4139ab["FileSystem: FileSystem"]
    L2_FileSystem_c779b9a743["FileSystem: FileSystem"]
    L2_FileSystem_f833559a1b["FileSystem: FileSystem"]
    L2_FileSystem_9fc21d41ad["FileSystem: FileSystem"]
    L2_FileSystem_d0bdb4828f["FileSystem: FileSystem"]
    L2_FirmwareHandoff_2ad8bc33fc["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_0b5382e29d["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_67dcd1043b["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_c8ef942b11["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_2016896632["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_3a972ac1e6["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_8689135ca3["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_2c3b64721a["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_2648c10441["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_9b84846f0b["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_8f29a89ef7["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_47fed57eb3["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_a1b12b0289["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_c46c1f8d46["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_f025b46a58["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_0c9074d1bb["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_f2a23fa0a3["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_63a1e4f254["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_896eaf5497["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_12ab4a21f3["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_b4585022d2["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_dc8c30b122["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_c34c70aa6a["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_b5091e8263["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_4c708def51["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_79a0867d44["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_f6f7a49855["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_1f168836fe["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_618fcb98a2["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_33b5bc2a67["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_43d527f97f["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_848541c1db["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_a0ddbc2cc1["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_2ea285bab2["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_41dd2607d8["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_a2bbc6b186["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_fcb33230a3["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_9bfbedda14["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_56118bbd46["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_72819af9c8["FirmwareHandoff: FirmwareHandoff"]
    L2_FirmwareHandoff_252e27359d["FirmwareHandoff: FirmwareHandoff"]
    L2_IRQController_d4f14279f6["IRQController: IRQController"]
    L2_Inode_3a41fad5c0["Inode: Inode"]
    L2_KernelHeap_b92a03f450["KernelHeap: KernelHeap"]
    L2_KernelHeap_90b7701d22["KernelHeap: KernelHeap"]
    L2_KernelHeap_11eecf42fb["KernelHeap: KernelHeap"]
    L2_KernelHeap_c0d863ea6e["KernelHeap: KernelHeap"]
    L2_KernelHeap_19f8f30f31["KernelHeap: KernelHeap"]
    L2_KernelHeap_45c577525e["KernelHeap: KernelHeap"]
    L2_Lock_7db4fa2bfb["Lock: Lock"]
    L2_Logger_cf8c992995["Logger: Logger"]
    L2_Logger_c25d034a4c["Logger: Logger"]
    L2_Logger_5519af5c66["Logger: Logger"]
    L2_Logger_aa5e8f155a["Logger: Logger"]
    L2_Logger_687160802c["Logger: Logger"]
    L2_Logger_dc15ebebf0["Logger: Logger"]
    L2_MMUInit_577335d912["MMUInit: MMUInit"]
    L2_ModeSwitch_60d7847db3["ModeSwitch: ModeSwitch"]
    L2_NetStack_c754c47dc1["NetStack: NetStack"]
    L2_PageTable_b6aebb4d8a["PageTable: PageTable"]
    L2_PageTable_4712218cf0["PageTable: PageTable"]
    L2_PageTable_349b807e29["PageTable: PageTable"]
    L2_PageTable_2aefd9e781["PageTable: PageTable"]
    L2_PageTable_3f1f65f869["PageTable: PageTable"]
    L2_PageTable_bb84ed335a["PageTable: PageTable"]
    L2_PageTable_bc54c4a70f["PageTable: PageTable"]
    L2_PageTable_48826e6b18["PageTable: PageTable"]
    L2_PageTable_99b030f1e0["PageTable: PageTable"]
    L2_PageTable_f5eabe7d3f["PageTable: PageTable"]
    L2_PageTable_71e2e65ae9["PageTable: PageTable"]
    L2_PageTable_4b173b4eaa["PageTable: PageTable"]
    L2_PageTable_a7d75e2e3b["PageTable: PageTable"]
    L2_PageTable_2cc13ec0b0["PageTable: PageTable"]
    L2_PageTable_68ed2ba073["PageTable: PageTable"]
    L2_PageTable_86086b9438["PageTable: PageTable"]
    L2_PageTable_3c8f7c2ae2["PageTable: PageTable"]
    L2_PageTable_2eec209085["PageTable: PageTable"]
    L2_PageTable_5b2866d82c["PageTable: PageTable"]
    L2_PageTable_0118cbf2bf["PageTable: PageTable"]
    L2_PageTable_ea4f34733f["PageTable: PageTable"]
    L2_PageTable_84929bd8b5["PageTable: PageTable"]
    L2_Panic_463d2dd0f2["Panic: Panic"]
    L2_Pipe_c6b5e4b297["Pipe: Pipe"]
    L2_Pipe_5f81902596["Pipe: Pipe"]
    L2_Pipe_7aa2662ce9["Pipe: Pipe"]
    L2_Pipe_943586cd62["Pipe: Pipe"]
    L2_Pipe_31ac19a437["Pipe: Pipe"]
    L2_Pipe_223075c1b4["Pipe: Pipe"]
    L2_Pipe_e2e36a63c2["Pipe: Pipe"]
    L2_Pipe_5f5c0bae9f["Pipe: Pipe"]
    L2_Pipe_286042a216["Pipe: Pipe"]
    L2_Pipe_81966025b1["Pipe: Pipe"]
    L2_Pipe_3245ba74c7["Pipe: Pipe"]
    L2_Pipe_22f9313ac8["Pipe: Pipe"]
    L2_Process_411361b613["Process: Process"]
    L2_Process_59d493005e["Process: Process"]
    L2_Process_3b1b0efdaa["Process: Process"]
    L2_Process_f52a5550b2["Process: Process"]
    L2_Process_d9abebc089["Process: Process"]
    L2_Process_3e8007c3e8["Process: Process"]
    L2_Process_3621466957["Process: Process"]
    L2_Process_4cfe44970f["Process: Process"]
    L2_Process_79a3d13492["Process: Process"]
    L2_Process_4c1adfd015["Process: Process"]
    L2_Process_334d799a96["Process: Process"]
    L2_Process_7249897fdb["Process: Process"]
    L2_Process_2f930f6cd7["Process: Process"]
    L2_Process_da204cda82["Process: Process"]
    L2_Process_d7f1bf0870["Process: Process"]
    L2_Process_082128e9a9["Process: Process"]
    L2_Process_edeec67b22["Process: Process"]
    L2_Process_79b9efd8bd["Process: Process"]
    L2_Scheduler_7cbca52ada["Scheduler: Scheduler"]
    L2_SignalIPC_a66b6c1b7e["SignalIPC: SignalIPC"]
    L2_SignalIPC_4f4d0b81f2["SignalIPC: SignalIPC"]
    L2_SignalIPC_120e92020d["SignalIPC: SignalIPC"]
    L2_SignalIPC_5eab3df863["SignalIPC: SignalIPC"]
    L2_SignalIPC_6704fc4e0f["SignalIPC: SignalIPC"]
    L2_SignalIPC_7e2872a931["SignalIPC: SignalIPC"]
    L2_SignalIPC_473f5f2b7f["SignalIPC: SignalIPC"]
    L2_SignalIPC_58c51654f1["SignalIPC: SignalIPC"]
    L2_SignalIPC_b109c7db8a["SignalIPC: SignalIPC"]
    L2_SignalIPC_61ee20b088["SignalIPC: SignalIPC"]
    L2_SignalIPC_7efd08f703["SignalIPC: SignalIPC"]
    L2_SignalIPC_e535ce4fc7["SignalIPC: SignalIPC"]
    L2_SignalIPC_9bfe1b2049["SignalIPC: SignalIPC"]
    L2_SignalIPC_9200957787["SignalIPC: SignalIPC"]
    L2_SignalIPC_198eb76eb5["SignalIPC: SignalIPC"]
    L2_SignalIPC_7a1a580a4c["SignalIPC: SignalIPC"]
    L2_SignalIPC_b23f930926["SignalIPC: SignalIPC"]
    L2_SignalIPC_52235ccf6e["SignalIPC: SignalIPC"]
    L2_SignalIPC_b78c5732cb["SignalIPC: SignalIPC"]
    L2_SignalIPC_48ce907172["SignalIPC: SignalIPC"]
    L2_SignalIPC_71782d0938["SignalIPC: SignalIPC"]
    L2_SignalIPC_5e77ee33cf["SignalIPC: SignalIPC"]
    L2_SignalIPC_e441cbe48f["SignalIPC: SignalIPC"]
    L2_SignalIPC_e446e49754["SignalIPC: SignalIPC"]
    L2_SignalIPC_27f8057ac8["SignalIPC: SignalIPC"]
    L2_SignalIPC_da82879b2b["SignalIPC: SignalIPC"]
    L2_SpinLock_ed5d8da1f8["SpinLock: SpinLock"]
    L2_SyscallHandler_de9687aa03["SyscallHandler: SyscallHandler"]
    L2_TargetPlatform_607586afdf["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_3d1704a760["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_01fd050282["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_af21e0e3bc["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_dcbe01939a["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_de82830139["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_31a0b88055["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_537e3154b3["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_4231c08d63["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_d3a2fc62b3["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_26a4d8c616["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_ade27e5419["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_394738d2d6["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_b7cbed23e0["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_886f210063["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_bee2d79a5a["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_b4a522c8b6["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_134624a5b7["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_f736412d4c["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_160086c51b["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_da1d996216["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_e53b9e31e5["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_6b2a907c44["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_e185c942f4["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_5e477027a1["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_adabe7f48b["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_47bab20d5c["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_dfa5b570da["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_6205910b68["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_0e13b948a7["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_b3265c520b["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_b54cd47c1c["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_7e9551172b["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_8053c108e3["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_4265243cc5["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_b60c977868["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_25b60dbd0d["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_9a46389848["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_ef32af4ea4["TargetPlatform: TargetPlatform"]
    L2_TargetPlatform_f22fdbf1e4["TargetPlatform: TargetPlatform"]
    L2_TestHarness_833efdaf75["TestHarness: TestHarness"]
    L2_TrapFrame_0e0a4cbf64["TrapFrame: TrapFrame"]
    L2_TrapVector_ccd6e67db1["TrapVector: TrapVector"]
    L2_UserRet_c609f96eca["UserRet: UserRet"]
    L2_VMAllocator_f7f2e06a58["VMAllocator: VMAllocator"]
    L2_VirtioDriver_bddfb64209["VirtioDriver: VirtioDriver"]
    L2_BootEntry_1d4a70760e -->|"depends_on"| L2_FirmwareHandoff_2ad8bc33fc
    L2_BootEntry_1d4a70760e -->|"triggers"| L2_MMUInit_577335d912
    L2_MMUInit_577335d912 -->|"maps"| L2_PageTable_4712218cf0
    L2_Scheduler_7cbca52ada -->|"triggers"| L2_Context_cac9543bf3
    L2_Scheduler_7cbca52ada -->|"schedules"| L2_Process_59d493005e
    L2_FileSystem_b5d09a04f5 -->|"depends_on"| L2_BlockDevice_c2340cf2ba
    L2_BlockDevice_c2340cf2ba -->|"depends_on"| L2_BlockCache_1bf979fb09
    L2_Driver_1093002b6c -->|"depends_on"| L2_IRQController_d4f14279f6
